ERREUR SQL : 13 Apr 2018 - 7:15:39.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:16:26.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:20:01.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:23:04.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:24:55.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:25:41.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:26:01.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:26:17.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:27:24.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:27:32.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
        VALUES ('', '', '', '/img/preuve/preuve1.png', ''); : (Incorrect date value: '' for column 'date' at row 1) 
ERREUR SQL : 13 Apr 2018 - 7:44:42.000000 -->  : (Query est vide) 
ERREUR SQL : 13 Apr 2018 - 7:45:24.000000 -->  : (Query est vide) 
ERREUR SQL : 13 Apr 2018 - 7:49:22.000000 -->  : (Query est vide) 
ERREUR SQL : 13 Apr 2018 - 7:49:43.000000 -->  : (Query est vide) 
ERREUR SQL : 13 Apr 2018 - 8:24:19.000000 --> INSERT INTO `preuve` (`intitule`, `date`, `prix`, `photo`, `description`) 
            VALUES ('', '', '', '', ''); : (Incorrect date value: '' for column 'date' at row 1) 
